name: flutter_application_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.2.0
  material_design_icons_flutter: 5.0.6595
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  dio: ^4.0.6
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.6
  geolocator: ^8.2.1
  table_calendar: ^2.3.1
  location: ^4.2.0
  modal_bottom_sheet: ^2.0.1
  expandable_bottom_sheet: ^1.1.1+1
  snapping_sheet: ^3.1.0
  cupertino_icons: ^1.0.2
  geocoding: ^2.0.4
  http: ^0.13.4
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
 # draggable_bottom_sheet: ^0.1.2
  google_place: ^0.4.7
  flutter_form_builder: ^6.2.0
 # flutter_clean_calendar: ^1.1.0
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  flutter_auth_buttons: ^0.9.0
  flutter_svg: ^0.18.0
  flutter_swiper: ^1.1.6
  intl: ^0.17.0
  package_info: ^0.4.3
  datetime_picker_formfield: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  flutter_lints: ^2.0.0


flutter:


  
  uses-material-design: true

  assets :
    - assets/images/
  
